program Mba;



uses
  Forms,
  Main in 'Src\Main.pas' {MainForm},
  Acceso in 'Src\Acceso.pas' {frmAcceso},
  DM_MBA in 'Src\DM_MBA.pas' {DM1: TDataModule},
  MsgError in 'Src\MsgError.pas' {frmMsgError},
  SIE in 'Src\SIE.pas' {frmSIE},
  AcercaDe in 'Src\AcercaDe.pas' {AboutBox},
  Splash02 in 'Src\Splash02.pas' {Splash},
  CapNC in 'Src\CapNC.pas' {frmCapNC},
  PendientesFam in 'Src\PendientesFam.pas' {frmPendientesFam},
  Proveedores in 'Src\Proveedores.pas' {frmProveedores},
  ClsPrintTxt in 'Src\ClsPrintTxt.pas',
  ClsProveedor in 'Src\ClsProveedor.pas',
  ClsSucursal in 'Src\ClsSucursal.pas',
  SelPedimentos in 'Src\SelPedimentos.pas' {frmPedimentos},
  SelTabla in 'Src\SelTabla.pas' {frmSelTabla},
  EnvioFac in 'Src\EnvioFac.pas' {frmEnvioFac},
  OpcionesF1 in 'Src\OpcionesF1.pas' {frmOpcF1},
  ClsTipoDoc in 'Src\ClsTipoDoc.pas',
  PrintTest in 'Src\PrintTest.pas' {frmPrintTest},
  Doc_Pagos in 'Src\Doc_Pagos.pas' {frmDocPagos},
  Constants_App in 'Src\Constants_App.pas',
  VerImagen in 'Src\VerImagen.pas' {frmVerImagen},
  RepFacRango in 'Src\RepFacRango.pas' {freFacRango: TFrame},
  RepCobMes in 'Src\RepCobMes.pas' {freCobMes: TFrame},
  Script in 'Src\Script.pas' {frmScript},
  Respaldo in 'Src\Respaldo.pas' {frmRespaldo},
  ClsProducto in 'Src\ClsProducto.pas',
  ClsMailer in 'Src\ClsMailer.pas',
  ClsUser in 'Src\ClsUser.pas',
  SelDocF2 in 'Src\SelDocF2.pas' {frmSelDocF2},
  ClsCostos in 'Src\ClsCostos.pas',
  BackOrder in 'Src\BackOrder.pas' {frmBackOrder},
  IBF_Users in 'Src\IBF_Users.pas' {frmUsers},
  Mapper in 'Src\Mapper.pas' {frmMapper},
  ClsCliente in 'Src\ClsCliente.pas',
  RepExisPrecio in 'Src\RepExisPrecio.pas' {freExisPrecio: TFrame},
  ClsTablas in 'Src\ClsTablas.pas',
  Repo_Costos in 'Src\Repo_Costos.pas' {frmRep_Costos},
  Monedas in 'Src\Monedas.pas' {frmMonedas},
  ClsAgente in 'Src\ClsAgente.pas',
  Doc_AlmacenRIH in 'Src\Doc_AlmacenRIH.pas' {frmDocs_AlmacenRIH},
  Tablas in 'Src\Tablas.pas' {frmTablas},
  Doc_Devo in 'Src\Doc_Devo.pas' {frmDocs_Devo},
  Compras in 'Src\Compras.pas' {frmCompras},
  RepEdoCtaDetP in 'Src\RepEdoCtaDetP.pas' {freEdoCtaDetP: TFrame},
  Queries in 'Src\Queries.pas' {frmQueries},
  PedimentosAct in 'Src\PedimentosAct.pas' {frmPedimentosAct},
  Etiquetas in 'Src\Etiquetas.pas' {frmEtiquetas},
  ConceptosDocto in 'Src\ConceptosDocto.pas' {frmConceptosDoc},
  ClsAsociaDoc in 'Src\ClsAsociaDoc.pas',
  Productos in 'Src\Productos.pas' {frmProductos},
  NotaCargoImpre in 'Src\NotaCargoImpre.pas' {frmNotaCargoImpre},
  Agentes in 'Src\Agentes.pas' {frmAgentes},
  Clientes in 'Src\Clientes.pas' {frmClientes},
  Rep_SelDoc in 'Src\Rep_SelDoc.pas' {frmRepSelDoc},
  ConfigSys in 'Src\ConfigSys.pas' {frmConfigSys},
  RepBackOrderCO in 'Src\RepBackOrderCO.pas' {freBackOrderCO: TFrame},
  RepValuaExis in 'Src\RepValuaExis.pas' {freValuaExis: TFrame},
  SelDoc in 'Src\SelDoc.pas' {frmSelDoc},
  RepArtBajaRota in 'Src\RepArtBajaRota.pas' {freArtBajaRota: TFrame},
  RepRelOC in 'Src\RepRelOC.pas' {freRelOC: TFrame},
  RepCarteraProv in 'Src\RepCarteraProv.pas' {freCarteraProv: TFrame},
  ACL in 'Src\ACL.pas' {frmACL},
  RepCobAgente in 'Src\RepCobAgente.pas' {freCobAgente: TFrame},
  RepCarAgente in 'Src\RepCarAgente.pas' {freCarAgente: TFrame},
  InvFisico in 'Src\InvFisico.pas' {frmInvFisico},
  TranspSearch in 'Src\TranspSearch.pas' {fraTransp: TFrame},
  ProveedorSearch in 'Src\ProveedorSearch.pas' {fraProveedor: TFrame},
  RepValuaInve in 'Src\RepValuaInve.pas' {freValuaInve: TFrame},
  RepCobranzaTipo in 'Src\RepCobranzaTipo.pas' {freCobranzaTipo: TFrame},
  dbExcel in 'Src\dbExcel.pas' {frmMiniExcel},
  RepAuxMovCte in 'Src\RepAuxMovCte.pas' {freAuxMovCte: TFrame},
  RepRentabAgente in 'Src\RepRentabAgente.pas' {freRentabAgente: TFrame},
  RepDiaVta in 'Src\RepDiaVta.pas' {freDiaVta: TFrame},
  RepVtaCteProd in 'Src\RepVtaCteProd.pas' {freVtaCteProd: TFrame},
  RepCompraProv in 'Src\RepCompraProv.pas' {freCompraProv: TFrame},
  Usuarios in 'Src\Usuarios.pas' {frmUsuarios},
  RepBackOrderInve in 'Src\RepBackOrderInve.pas' {freBackOrderInve: TFrame},
  ClsDoc in 'Src\ClsDoc.pas',
  RepDiaCompra in 'Src\RepDiaCompra.pas' {freDiaCompra: TFrame},
  RepCompAgte in 'Src\RepCompAgte.pas' {freCompAgte: TFrame},
  RepProvProd in 'Src\RepProvProd.pas' {freProvProd},
  AgenteSearch in 'Src\AgenteSearch.pas' {fraAgente: TFrame},
  RepCteSinVta in 'Src\RepCteSinVta.pas' {freCteSinVta: TFrame},
  RepDirProv in 'Src\RepDirProv.pas' {freDirProv: TFrame},
  Reportes in 'Src\Reportes.pas' {frmReportes},
  ProSaldoNCg in 'Src\ProSaldoNCg.pas' {fraSaldoNCg: TFrame},
  ProCierreInve in 'Src\ProCierreInve.pas' {fraCierreInve: TFrame},
  ProBackOrder2 in 'Src\ProBackOrder2.pas' {fraBackOrder: TFrame},
  RepCatProv in 'Src\RepCatProv.pas' {freCatProv: TFrame},
  RepCompAnualAgte in 'Src\RepCompAnualAgte.pas' {freCompAnualAgte: TFrame},
  RepCompCte2 in 'Src\RepCompCte2.pas' {freCompCte2: TFrame},
  RepEstadExis in 'Src\RepEstadExis.pas' {freEstadExis: TFrame},
  ProAjusteExis in 'Src\ProAjusteExis.pas' {fraAjusteExis: TFrame},
  Conexion in 'Src\Conexion.pas' {frmConexion},
  UsersCon in 'Src\UsersCon.pas' {frmUsersCon},
  ClsAplicacion in 'Src\ClsAplicacion.pas',
  Procesos in 'Src\Procesos.pas' {frmProcesos},
  ProCierreMes in 'Src\ProCierreMes.pas' {fraCierreMes: TFrame},
  RepCompAnualCte in 'Src\RepCompAnualCte.pas' {freCompAnualCte: TFrame},
  HHelp in 'Src\HHelp.pas' {frmHHelp},
  RepVtaCte in 'Src\RepVtaCte.pas' {freVtaCte: TFrame},
  MsgBar in 'Src\MsgBar.pas' {frmMsgBar},
  Avance in 'Src\Avance.pas' {frmAvance},
  Dirs_Entrega in 'Src\Dirs_Entrega.pas' {fraDirs_Entrega: TFrame},
  Saldos in 'Src\Saldos.pas' {frmSaldos},
  ProCteSinVta2 in 'Src\ProCteSinVta2.pas' {fraCteSinVta: TFrame},
  ProCambioProdFam in 'Src\ProCambioProdFam.pas' {fraCambioProdFam: TFrame},
  FamiliaSearch in 'Src\FamiliaSearch.pas' {fraFamilia: TFrame},
  ProductoSearch in 'Src\ProductoSearch.pas' {fraProducto: TFrame},
  ProImpProvee in 'Src\ProImpProvee.pas' {fraImpProvee: TFrame},
  SelCodDes in 'Src\SelCodDes.pas' {frmSelect},
  RepBackFam in 'Src\RepBackFam.pas' {freBackFam: TFrame},
  ProCambioCodFam in 'Src\ProCambioCodFam.pas' {fraCambioCodFam: TFrame},
  RepEstadProvProd in 'Src\RepEstadProvProd.pas' {freEstadProvProd: TFrame},
  ProBorrarAjustes in 'Src\ProBorrarAjustes.pas' {fraBorrarAjustes: TFrame},
  ProCambioCostos in 'Src\ProCambioCostos.pas' {fraCambioCostos: TFrame},
  ProExpProvee in 'Src\ProExpProvee.pas' {fraExpProvee: TFrame},
  Doc_NotasCargo in 'Src\Doc_NotasCargo.pas' {frmDocNotasCargo},
  RepCatCte in 'Src\RepCatCte.pas' {freCatCte: TFrame},
  RepSaldosClientes in 'Src\RepSaldosClientes.pas' {freSaldosClientes: TFrame},
  RepEdoCta in 'Src\RepEdoCta.pas' {freEdoCta: TFrame},
  RepDirCte2 in 'Src\RepDirCte2.pas' {freDirCte2: TFrame},
  RepCompAnualProd in 'Src\RepCompAnualProd.pas' {freCompAnualProd: TFrame},
  RepEstadCteProd in 'Src\RepEstadCteProd.pas' {freEstadCteProd: TFrame},
  RepTipoDocto in 'Src\RepTipoDocto.pas' {freTipoDocto: TFrame},
  RepKardex in 'Src\RepKardex.pas' {freKardex: TFrame},
  RepInvActual in 'Src\RepInvActual.pas' {freInvActual: TFrame},
  RepComprasBack in 'Src\RepComprasBack.pas' {freComprasBack: TFrame},
  ClsEmpresa in 'Src\ClsEmpresa.pas',
  EstadoSearch in 'Src\EstadoSearch.pas' {fraEstado: TFrame},
  Empresas in 'Src\Empresas.pas' {frmEmpresas},
  CiudadSearch in 'Src\CiudadSearch.pas' {fraCiudad: TFrame},
  FormFisAct2 in 'Src\FormFisAct2.pas' {frmFisAct2},
  RepMovAlmac in 'Src\RepMovAlmac.pas' {freMovAlmac: TFrame},
  FotosProd in 'Src\FotosProd.pas' {frmFotos},
  fraImage in 'Src\fraImage.pas' {fraImagen: TFrame},
  ArtCapturaF1 in 'Src\ArtCapturaF1.pas' {frmArtCapF1},
  Doc_Compras in 'Src\Doc_Compras.pas' {frmDocs_Compras},
  RepCompCte in 'Src\RepCompCte.pas' {freCompCte: TFrame},
  RepDirCte in 'Src\RepDirCte.pas' {freDirCte: TFrame},
  ProImpProd in 'Src\ProImpProd.pas' {fraImpProd: TFrame},
  ProExpProd in 'Src\ProExpProd.pas' {fraExpProd: TFrame},
  RepEdoCtaP in 'Src\RepEdoCtaP.pas' {freEdoCtaP: TFrame},
  ImportarCFDI in 'Src\ImportarCFDI.pas' {frmImportarCFDI},
  RepBackOrderPro in 'Src\RepBackOrderPro.pas' {freBackOrderPro: TFrame},
  RepVtaAgente in 'Src\RepVtaAgente.pas' {freVtaAgente: TFrame},
  ProDescuentos in 'Src\ProDescuentos.pas' {fraDescuentos: TFrame},
  ConteoFisico in 'Src\ConteoFisico.pas' {frmConteoFisico},
  LibApp in 'Src\LibApp.pas',
  FormulaOneLib in 'Src\FormulaOneLib.pas',
  ProCambioCodProd in 'Src\ProCambioCodProd.pas' {fraCambioCodProd: TFrame},
  ParametrosAct in 'Src\ParametrosAct.pas' {frmParametrosAct},
  RepEdoCtaDet in 'Src\RepEdoCtaDet.pas' {freEdoCtaDet: TFrame},
  Almacenes in 'Src\Almacenes.pas' {frmAlmacenes},
  ProFisicoActual in 'Src\ProFisicoActual.pas' {fraFisicoActual: TFrame},
  TipoDocto in 'Src\TipoDocto.pas' {frmTipoDoc},
  Doc_Abonos in 'Src\Doc_Abonos.pas' {frmDocAbo},
  Familias in 'Src\Familias.pas' {frmFamilias},
  RepVtaFamilia in 'Src\RepVtaFamilia.pas' {freVtaFamilia: TFrame},
  RepAS in 'Src\RepAS.pas' {freAS: TFrame},
  RepClientesAtraso in 'Src\RepClientesAtraso.pas' {freClientesAtraso: TFrame},
  Doc_Cotiza in 'Src\Doc_Cotiza.pas' {frmDocsCotiza},
  Doc_Cargos in 'Src\Doc_Cargos.pas' {frmDocs},
  ProPrecio9 in 'Src\ProPrecio9.pas' {fraPrecio9: TFrame},
  RepSaldos in 'Src\RepSaldos.pas' {freSaldos: TFrame},
  SurtBack in 'Src\SurtBack.pas' {frmSYB},
  ClsParam in 'Src\ClsParam.pas',
  ArtRotacion in 'Src\ArtRotacion.pas' {frmArtRotacion},
  CostosFac in 'Src\CostosFac.pas' {frmCostosFac},
  Articulos in 'Src\Articulos.pas' {frmArticulos},
  Departamentos in 'Src\Departamentos.pas' {frmDepartamentos},
  CosteoEspecial in 'Src\CosteoEspecial.pas' {frmCosteoEsp},
  ParametrosCxC in 'Src\ParametrosCxC.pas' {frmParametrosCxC},
  CostosProd in 'Src\CostosProd.pas' {frmCostosProd},
  XRepRentab in 'Src\XRepRentab.pas' {frmXRepRentab},
  ClsUbicaciones in 'Src\ClsUbicaciones.pas',
  CambioLimCre in 'Src\CambioLimCre.pas' {frmCambioLimcre},
  XRepAS2 in 'Src\XRepAS2.pas' {frmXRepAS2},
  XRepVtaAvance in 'Src\XRepVtaAvance.pas' {frmXRepVtaAvance},
  XRepVtaFam in 'Src\XRepVtaFam.pas' {frmXRepVtaFam},
  XRepVtaSuc2 in 'Src\XRepVtaSuc2.pas' {frmXRepVtaSuc2},
  DownLoad in 'Src\DownLoad.pas' {frmDownLoad},
  RepComis in 'Src\RepComis.pas' {frmRepComis},
  RepComisAux in 'Src\RepComisAux.pas' {frmRepComisAux},
  RepBloqueados in 'Src\RepBloqueados.pas' {frmRepBloqueados},
  DepartamentosAct in 'Src\DepartamentosAct.pas' {frmDepartamentosAct},
  XAnalisisDesctos in 'Src\XAnalisisDesctos.pas' {frmAnalisisDesctos},
  ClienteAct in 'Src\ClienteAct.pas' {frmClienteAct},
  Conversion in 'Src\Conversion.pas' {frmConversion},
  CapFacturas in 'Src\CapFacturas.pas' {frmCapFacturas},
  ActDescuentos in 'Src\ActDescuentos.pas' {frmActDescuentos},
  XRepVtaSuc in 'Src\XRepVtaSuc.pas' {frmXRepVtaSuc},
  CambioCodigos in 'Src\CambioCodigos.pas' {frmCambioCodigos},
  FormFisAct in 'Src\FormFisAct.pas' {frmFisAct},
  CambioFam in 'Src\CambioFam.pas' {frmCambioFam},
  XCapPpto in 'Src\XCapPpto.pas' {frmXCapPpto},
  Ubicaciones_Producto in 'Src\Ubicaciones_Producto.pas' {frmUbicaciones_Producto},
  RepDocVentas in 'Src\RepDocVentas.pas' {frmRepDocVentas},
  CambioArt in 'Src\CambioArt.pas' {frmCambioArt},
  RepDocCobros in 'Src\RepDocCobros.pas' {frmRepDocCobros},
  XAutorizaCxC in 'Src\XAutorizaCxC.pas' {frmAutorizaCxC},
  Productos2 in 'Src\Productos2.pas' {frmProductos2},
  ProductoAct in 'Src\ProductoAct.pas' {frmProductoAct},
  ClsDirEntrega in 'Src\ClsDirEntrega.pas',
  ClsDepartamento in 'Src\ClsDepartamento.pas',
  ClsOrdenSurtido in 'Src\ClsOrdenSurtido.pas',
  Direct3D9 in 'C:\DesaBDS2006\WebCamDirectX\Common\DirectX\Direct3D9.pas',
  DirectDraw in 'C:\DesaBDS2006\WebCamDirectX\Common\DirectX\DirectDraw.pas',
  DirectShow9 in 'C:\DesaBDS2006\WebCamDirectX\Common\DirectX\DirectShow9.pas',
  DirectSound in 'C:\DesaBDS2006\WebCamDirectX\Common\DirectX\DirectSound.pas',
  DXTypes in 'C:\DesaBDS2006\WebCamDirectX\Common\DirectX\DXTypes.pas',
  Fotos in 'Src\Fotos.pas' {frmTomarFotos},
  Refacciones in 'Src\Refacciones.pas' {frmRefacciones},
  RefaccionesAct in 'Src\RefaccionesAct.pas' {frmRefaccionesAct},
  Recursos in 'Src\Recursos.pas' {frmRecursos},
  RecursosAct in 'Src\RecursosAct.pas' {frmRecursosAct},
  Doc_Almacen in 'Src\Doc_Almacen.pas' {frmDocs_Almacen},
  ClsRecurso in 'Src\ClsRecurso.pas',
  XRepInve in 'Src\XRepInve.pas' {frmXRepInve},
  RRepExistencias in 'Src\RRepExistencias.pas' {frmRRepExistencias},
  RRepConsumos in 'Src\RRepConsumos.pas' {frmRRepConsumos},
  RRepRequisiciones in 'Src\RRepRequisiciones.pas' {frmRRepRequisiciones},
  VFrames in 'C:\@DESAD7\WebCamDirectX\Common\VFrames.pas',
  VSample in 'C:\@DESAD7\WebCamDirectX\Common\VSample.pas',
  Graficas in 'Src\Graficas.pas' {frmGrafica},
  Mailer in 'Src\Mailer.pas' {frmMailer},
  XRepUltimasVentas in 'Src\XRepUltimasVentas.pas' {frmXRepUltimasVentas},
  XRepPolizas in 'Src\XRepPolizas.pas' {frmXRepPolizas},
  ClsPoliza in 'Src\ClsPoliza.pas',
  LayOutPolizas in 'Src\LayOutPolizas.pas' {frmLayoutPolizas},
  CambioCapturaPL in 'Src\CambioCapturaPL.pas',
  Prueba in 'Src\Prueba.pas' {frmPrueba},
  Doc_Factura in 'Src\Doc_Factura.pas' {frmDocsFac},
  ClsOC in 'Src\ClsOC.pas',
  OCompra in 'Src\OCompra.pas' {frmOCompra},
  SelDocF1 in 'Src\SelDocF1.pas' {frmSelDocF1},
  AnalisisCostos in 'Src\AnalisisCostos.pas' {frmAnalisisCostos},
  FacElecBase in 'Src\FacElecBase.pas' {frmFE},
  ClsMoneda in 'Src\ClsMoneda.pas',
  FE332 in 'Src\FE332.pas' {frmFE332},
  ClienteSearch in 'Src\ClienteSearch.pas' {fraCliente: TFrame},
  CalculaDescto in 'Src\CalculaDescto.pas' {frmCalculaDescto},
  Doc_Costos in 'Src\Doc_Costos.pas' {frmDoc_Costos},
  Ordenes_Surtido in 'Src\Ordenes_Surtido.pas' {frmOrdenes_Surtido},
  ClsCfdi33 in 'Src\ClsCfdi33.pas',
  Ubicaciones in 'Src\Ubicaciones.pas' {frmUbicaciones},
  CapturaLP in 'Src\CapturaLP.pas' {frmCapturaLP},
  Clientes2 in 'Src\Clientes2.pas' {frmClientes2},
  TablasComis in 'Src\TablasComis.pas' {frmTablasComis},
  ClsFamilia in 'Src\ClsFamilia.pas',
  AsignarSurtidor in 'Src\AsignarSurtidor.pas' {frmAsignarSurtidor},
  UbiProdAct in 'Src\UbiProdAct.pas' {frmUbiProdAct},
  ClsConcepto in 'Src\ClsConcepto.pas',
  UbiProdAct2 in 'Src\UbiProdAct2.pas' {frmUbiProdAct2},
  Estatus_Pedidos in 'Src\Estatus_Pedidos.pas' {frmEstat_Pedidos};

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := 'MBA Plus';
  f := TSplash.Create(Application) ;
  f.Show ;
  f.Update ;
  f.PutMessage ('Inicializando forma principal...');
  Application.CreateForm(TMainForm, MainForm);
  Application.CreateForm(TDM1, DM1);
  Application.CreateForm(TSplash, Splash);
  Application.CreateForm(TAboutBox, AboutBox);
  f.PutMessage ('Creando accesos a BD');
  f.PutMessage ('Inicializando Accesos...');
  Application.CreateForm(TfrmAcceso, frmAcceso);


  Application.Run;
end.
